"use client";

import { useEffect, useState } from "react";
import { askQuestion } from "@/lib/api";

interface AskDataProps {
  datasetId: string;
}

export default function AskData({ datasetId }: AskDataProps) {
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Clear the conversation when the dataset changes (e.g. after cleaning).
  useEffect(() => {
    setQuestion("");
    setAnswer(null);
    setError(null);
  }, [datasetId]);

  async function handleSubmit(event: React.FormEvent) {
    event.preventDefault();
    const trimmed = question.trim();
    if (!trimmed) return;

    setIsLoading(true);
    setError(null);
    setAnswer(null);
    try {
      const result = await askQuestion(datasetId, trimmed);
      setAnswer(result.answer);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Failed to get an answer");
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <div className="w-full max-w-4xl rounded-lg border border-gray-200 p-5 dark:border-gray-700">
      <h3 className="mb-3 text-xs font-semibold uppercase tracking-widest text-gray-400">
        Ask your data
      </h3>

      <form onSubmit={handleSubmit} className="flex flex-col gap-3">
        <textarea
          value={question}
          onChange={(e) => setQuestion(e.target.value)}
          placeholder="e.g. Which category has the highest average value? Are there any outliers?"
          rows={2}
          className="w-full resize-y rounded-md border border-gray-300 p-3 text-sm outline-none focus:border-blue-500 dark:border-gray-600 dark:bg-gray-900"
        />
        <button
          type="submit"
          disabled={isLoading || !question.trim()}
          className="self-start rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-blue-700 disabled:opacity-60"
        >
          {isLoading ? "Thinking…" : "Ask"}
        </button>
      </form>

      {error && <p className="mt-3 text-sm text-red-600">{error}</p>}

      {answer && (
        <div className="mt-4 rounded-md bg-gray-50 p-4 text-sm whitespace-pre-wrap dark:bg-gray-800">
          {answer}
        </div>
      )}

      <p className="mt-3 text-xs text-gray-400">
        Answers are generated by AI from your dataset&apos;s schema, summary
        statistics, and a sample of rows.
      </p>
    </div>
  );
}
